# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentioned_name', models.CharField(max_length=250)),
                ('anon_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('anon_id', models.CharField(max_length=250)),
                ('deleted', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies', models.IntegerField(default=0, verbose_name=b'Number of Replies')),
                ('archived', models.BooleanField(default=False, verbose_name=b'Is Archived?')),
                ('topic', models.CharField(default=b'Current', max_length=250, verbose_name=b'Topic')),
                ('latest_reply', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True)),
                ('original_poster', models.CharField(max_length=250)),
                ('course_id', models.CharField(max_length=250)),
                ('deleted', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-latest_reply'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Thread', verbose_name=b'Parent Thread'),
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Post', verbose_name=b'Post Mentioned'),
        ),
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threads.Thread', verbose_name=b'Thread Mentioned'),
        ),
    ]
