# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_pseudonym'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pseudonym',
            options={'ordering': ['category', 'name']},
        ),
    ]
