# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20160816_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='latest_reply',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
