# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20160819_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
