# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_notification_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['updated_date']},
        ),
    ]
