# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20160826_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
